package br.com.netmei.bean;
// Generated 20/10/2014 21:15:39 by Hibernate Tools 3.6.0

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;




/**
 * Empresa generated by hbm2java
 */
@Entity
public class Empresa  implements java.io.Serializable {

     @Id
     @GeneratedValue(strategy = GenerationType.SEQUENCE)
     private int idempresa;
     private String telefone;
     private String cep;
     private String endereco;
     private Integer numero;
     private String complemento;
     private String bairro;
     private String cidade;
     private String estado;
     private String razaosocial;

    public Empresa() {
    }

	
    public Empresa(int idempresa) {
        this.idempresa = idempresa;
    }
    public Empresa(int idempresa, String telefone, String cep, String endereco, Integer numero, String complemento, String bairro, String cidade, String estado, String razaosocial) {
       this.idempresa = idempresa;
       this.telefone = telefone;
       this.cep = cep;
       this.endereco = endereco;
       this.numero = numero;
       this.complemento = complemento;
       this.bairro = bairro;
       this.cidade = cidade;
       this.estado = estado;
       this.razaosocial = razaosocial;
    }
   
    public int getIdempresa() {
        return this.idempresa;
    }
    
    public void setIdempresa(int idempresa) {
        this.idempresa = idempresa;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getRazaosocial() {
        return this.razaosocial;
    }
    
    public void setRazaosocial(String razaosocial) {
        this.razaosocial = razaosocial;
    }




}


